language: python

# necessary for 3.7 due to https://github.com/PyTables/PyTables/issues/704
addons:
  apt:
    packages:
      - libhdf5-dev

matrix:
  include:
    - python: 2.7
    - python: 3.6
    - python: 3.7
    - python: 3.8

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .[full]

# command to run tests and examples, e.g. python setup.py test
script:
  - cd ./neuroml/test && nosetests -vs
  - cd ../examples && python run_all.py

services: mongodb
